[2021-03-22 09:19:01,232] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-22 09:19:06,443] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-22 09:19:11,831] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-22 09:19:13,785] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-22 09:19:15,812] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-22 09:19:21,078] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-22 09:19:23,122] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-22 09:19:30,275] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-22 09:19:32,374] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-22 09:19:36,337] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_cdesc_abnormal
[2021-03-22 09:19:44,076] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_cdesc_abnormal
[2021-03-22 09:19:53,781] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_edesc_abnormal
[2021-03-22 09:20:01,646] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_edesc_abnormal
[2021-03-22 09:52:01,999] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_001
[2021-03-22 09:52:13,425] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_001
[2021-03-22 09:52:23,640] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_001
[2021-03-22 09:52:34,563] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_001
[2021-03-22 09:52:44,618] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_002
[2021-03-22 09:52:54,891] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_002
[2021-03-22 09:53:05,115] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_002
[2021-03-22 09:53:15,396] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_003
[2021-03-22 09:53:25,619] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_003
[2021-03-22 09:53:36,031] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_003
[2021-03-22 09:53:46,658] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_001
[2021-03-22 09:54:09,045] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_001
[2021-03-22 09:54:31,196] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_001
[2021-03-22 09:54:54,094] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_001
[2021-03-22 09:55:16,319] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_002
[2021-03-22 09:55:28,323] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_002
[2021-03-22 09:55:40,385] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_002
[2021-03-22 09:55:52,326] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_003
[2021-03-22 09:56:04,420] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_003
[2021-03-22 09:56:17,458] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_003
[2021-03-22 10:26:08,208] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_wo_search
[2021-03-22 10:26:10,899] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration
[2021-03-22 10:36:24,826] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_wo_search
[2021-03-22 10:36:27,618] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration
[2021-03-22 10:38:12,527] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_wo_search
[2021-03-22 10:38:15,301] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration
[2021-03-22 11:14:54,393] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_wo_search
[2021-03-22 11:16:16,138] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_wo_search
[2021-03-22 11:18:25,908] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 11:18:34,029] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 11:19:03,498] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 11:19:48,365] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 11:20:01,060] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 11:20:20,007] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 11:20:39,226] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 11:51:30,302] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_wo_search
[2021-03-22 11:51:32,843] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 11:51:35,310] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 11:51:40,651] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 14:42:24,117] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_wo_search
[2021-03-22 14:42:26,841] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 14:42:29,782] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 14:42:35,270] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 14:42:37,537] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 14:42:46,706] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 14:42:56,039] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 14:43:04,998] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 14:54:05,449] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_wo_search
[2021-03-22 14:54:08,251] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 14:54:11,395] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 14:54:16,853] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_num_abnormal
[2021-03-22 14:54:19,128] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 14:54:28,498] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 14:54:37,826] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
[2021-03-22 14:54:47,039] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_Declaration_Cnumber_abnormal
